In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\Rakhi Bhardwaj\Desktop\mutual_fund_project\data\raw\kotak_bluechip.csv")

In [4]:
df.head()

         date       nav
0  23-06-2026  249.9814
1  22-06-2026  252.0694
2  19-06-2026  251.5713
3  18-06-2026  249.1553
4  17-06-2026  246.3925

In [6]:
df.shape

(3317, 2)

In [7]:
df.dtypes

date        str
nav     float64
dtype: object

In [9]:
df.isnull().sum()

date    0
nav     0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.columns

Index(['date', 'nav'], dtype='str')

In [14]:
df.describe()

               nav
count  3317.000000
mean    102.609585
std      76.276309
min      30.564300
25%      45.993200
50%      57.316300
75%     145.543600
max     281.108300

In [16]:
df.tail(1)

            date      nav
3316  07-01-2013  30.6076

In [17]:
len(df)

3317

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3317 entries, 0 to 3316
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    3317 non-null   str
 1   nav     3317 non-null   float64
dtypes: float64(1), str(1)
memory usage: 52.0 KB