In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\Rakhi Bhardwaj\Desktop\mutual_fund_project\data\raw\nippon_large_cap.csv")

In [3]:
df.head()

         date       nav
0  23-06-2026  100.4605
1  22-06-2026  101.3654
2  19-06-2026  100.7824
3  18-06-2026  100.9901
4  17-06-2026  100.6040

In [5]:
df.size

6628

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.dtypes

date        str
nav     float64
dtype: object

In [8]:
df.isnull().sum()

date    0
nav     0
dtype: int64

In [9]:
df.columns

Index(['date', 'nav'], dtype='str')

In [11]:
df.describe()

               nav
count  3314.000000
mean     46.341793
std      27.756728
min      12.219100
25%      24.991250
50%      34.977350
75%      60.270925
max     106.127200

In [12]:
df.tail(10)

            date      nav
3304  15-01-2013  14.8315
3305  14-01-2013  14.7844
3306  11-01-2013  14.6421
3307  10-01-2013  14.6784
3308  09-01-2013  14.7249
3309  08-01-2013  14.7197
3310  07-01-2013  14.7718
3311  04-01-2013  14.8037
3312  03-01-2013  14.7305
3313  02-01-2013  14.6967

In [13]:
len(df)

3314

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3314 entries, 0 to 3313
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    3314 non-null   str
 1   nav     3314 non-null   float64
dtypes: float64(1), str(1)
memory usage: 51.9 KB