In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\Rakhi Bhardwaj\Desktop\mutual_fund_project\data\raw\hdfc_nav.csv")

In [4]:
print(df.head())

         date       nav
0  23-06-2026  203.5443
1  22-06-2026  204.1263
2  19-06-2026  202.0761
3  18-06-2026  200.9565
4  17-06-2026  199.8302

In [5]:
df.shape

(3107, 2)

In [6]:
df.dtypes

date        str
nav     float64
dtype: object

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3107 entries, 0 to 3106
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    3107 non-null   str
 1   nav     3107 non-null   float64
dtypes: float64(1), str(1)
memory usage: 48.7 KB

In [8]:
df.head(10)

         date       nav
0  23-06-2026  203.5443
1  22-06-2026  204.1263
2  19-06-2026  202.0761
3  18-06-2026  200.9565
4  17-06-2026  199.8302
5  16-06-2026  198.6152
6  15-06-2026  198.0320
7  12-06-2026  196.5577
8  11-06-2026  192.6722
9  10-06-2026  193.4371

In [9]:
df.tail()

            date      nav
3102  22-11-2013  12.7775
3103  21-11-2013  12.7957
3104  20-11-2013  12.9549
3105  19-11-2013  13.1068
3106  18-11-2013  13.0894

In [10]:
df.isnull().sum()

date    0
nav     0
dtype: int64